### ISSUE TITLE
How can I run test cases?

### ISSUE THREAD

**Issue by wenchao-hao** [open-iscsi/open-iscsi#311] opened 2022-02-25 16:49 UTC
Recently, I want to run test cases in test/ direction, while there are not enough documents about it.

Normally, execute following command:

```
python3 -m unittest discover
```

This would fork much sub-process, no log printed, and would hang for about 12 hours and did not finish(killed by ctrl+C), is this ok?

What's more I made few changes to regression.sh, this scripts can run it successfully after changes.

```
sh -x regression.sh iqn.2003-01.org.linux-iscsi.localhost.test:sn.12345678abcd 192.168.1.10 /dev/sda
```

Which scripts should we use?

**Comment by gonzoleeman** [comment] 2022-02-26 20:18
The shell-script-based regression.sh is outdated. Rather than support or update it, I created test-open-iscsi.py. I started documenting this in the README in the test directory, but I never finished.

Did you try "./test-open-iscsi.py --help"?

There are several prerequisites if you want to run this, which I should document:

1. You need to install fio and bonnie++ (and they need to be in the PATH)
2. You need to be root for testing, of course, since it runs iscsiadm commands
3. You need an iSCSI target that you can reach. I used 10Gig. I left off ACLs on my target
4. You need to know the IQN of your target, it's IP address, and which disk will show up when you log into that target (e.g. /dev/sdc).
5. I usually manually log into the target from the command line, to check things and write down the /dev/sdX path, then log back out
6. Then you can run the test, e.g.: ./test-open-iscsi.py -v -f -t IQN-of-your-TARGET -i IP-ADDRESS-of-tgt -D /dev/sdX

I just tested this, so it should be working. It takes quite a while for it to run. I will try the unittest when it finishes, to maybe see why it is hanging. But the "approved" way of running this is via the python script, as shown. Note: you can run:

    # ./test-open-iscsi.py -l

To list the tests, as the help message details.

**Comment by gonzoleeman** [comment] 2022-02-27 19:01
Note: I found one issue in the tests, and I'm cleaning up a few things there, in general. So if you see any issues, please let me know.

I am also adding a detailed README on the python tests.

**Comment by wenchao-hao** [comment] 2022-02-28 02:30
> The shell-script-based regression.sh is outdated. Rather than support or update it, I created test-open-iscsi.py. I started documenting this in the README in the test directory, but I never finished.
> 
> Did you try "./test-open-iscsi.py --help"?
> 
> There are several prerequisites if you want to run this, which I should document:
> 
> 1. You need to install fio and bonnie++ (and they need to be in the PATH)
> 2. You need to be root for testing, of course, since it runs iscsiadm commands
> 3. You need an iSCSI target that you can reach. I used 10Gig. I left off ACLs on my target
> 4. You need to know the IQN of your target, it's IP address, and which disk will show up when you log into that target (e.g. /dev/sdc).
> 5. I usually manually log into the target from the command line, to check things and write down the /dev/sdX path, then log back out
> 6. Then you can run the test, e.g.: ./test-open-iscsi.py -v -f -t IQN-of-your-TARGET -i IP-ADDRESS-of-tgt -D /dev/sdX
> 
> I just tested this, so it should be working. It takes quite a while for it to run. I will try the unittest when it finishes, to maybe see why it is hanging. But the "approved" way of running this is via the python script, as shown. Note: you can run:
> 
> ```
> # ./test-open-iscsi.py -l
> ```
> 
> To list the tests, as the help message details.

Thank you for your answer, I did not specify the target name and ip address, the testcases runs ok now

**Comment by wenchao-hao** [comment] 2022-02-28 11:47
I meet an error with following with command:

```
./test-open-iscsi.py -v -f -D /dev/sdc -t iqn.2003-01.org.linux-iscsi.localhost.test:sn.12345678abcd -i 9.84.111.6
```

The error log is :

```
* ImmediateData = Yes
* InitialR2T = No
* HeaderDigest = None,CRC32C
* DataDigest = None,CRC32C
* FirstBurstLength = 262144
* MaxBurstLength = 16776192
* MaxRecvDataSegmentLength = 131072
* MaxOutstandingR2T = 1

======================================================================
ERROR: test_HdrDigest_on_DataDigest_off (harness.tests.TestRegression) [Testing FirstBurst=8192 MaxBurts=4096 MaxRecv=4096] (i=2)
Test With Header Digest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/open-iscsi/test/harness/tests.py", line 127, in test_HdrDigest_on_DataDigest_off
    self.run_the_rest()
  File "/root/open-iscsi/test/harness/tests.py", line 156, in run_the_rest
    (res, reason) = util.run_parted()
  File "/root/open-iscsi/test/harness/util.py", line 342, in run_parted
    return (res, resason)
NameError: name 'resason' is not defined

----------------------------------------------------------------------
Ran 1 test in 224.992s

FAILED (errors=1)
```

**Comment by gonzoleeman** [comment] 2022-02-28 18:02
Yes, I found this issue too, right away. :(

It's just a misspelling of "reason". You can fix it yourself, if you wish.

I've just pushed my test branch that fixes this issue and improves the tests a bit, including adding a python-specific README file. If you like, please check out https://github.com/gonzoleeman/open-iscsi, branch improve-python-selftest.

I believe you can just copy the "test" subdirectory from my branch and try it on your version of open-iscsi.

**Comment by gonzoleeman** [comment] 2022-02-28 19:49
Also, FWIW, I've noticed a problem running some tests with 512-byte block size. I'm trying to run all 960 tests, to see how long that takes, but the system pretty consistently hangs. Right now, I'm running all tests using a single blocksize, one block size at a time. Each block size test should take maybe 1.5 hours?

**Comment by wenchao-hao** [comment] 2022-03-01 09:12
> Also, FWIW, I've noticed a problem running some tests with 512-byte block size. I'm trying to run all 960 tests, to see how long that takes, but the system pretty consistently hangs. Right now, I'm running all tests using a single blocksize, one block size at a time. Each block size test should take maybe 1.5 hours?

I meet the hang issue too with your ```improve-python-selftest``` branch, while I can not fix it because I do not understand the test suite now. 

I have following advises which might make these tests better:

1. simulate iscsi target with tools such as ```tgtadm``` so that the tests can run within a single device. ```tgtadm``` commands like following is helpful:

```
tgtadm --lld iscsi --mode target --op new --tid 1 --targetname iqn.xxx.xxxx
tgtadm --lld iscsi --mode logicalunit --op new --tid 1 --lun 1 --backing-store xxx
tgtadm --lld iscsi --mode target --op bind --tid 1 --initiator-address ALL
```

2. It takes too long to run these cases, we might splict to two kind of jobs: heavyweight and lightweight. For heavyweight tests, run all test cases, we do not care how long it takes. For  lightweight tests, make sure it can finish fastly, maybe we can exclude bonnie++ and fio tests from the lightweight tests.

3. Extent the coverage to more core scenario, such as CHAP.

**Comment by gonzoleeman** [comment] 2022-03-01 16:57
On Mar 1, 2022, at 1:13 AM, Wenchao Hao ***@***.***> wrote:
> 
> 
> Also, FWIW, I've noticed a problem running some tests with 512-byte block size. I'm trying to run all 960 tests, to see how long that takes, but the system pretty consistently hangs. Right now, I'm running all tests using a single blocksize, one block size at a time. Each block size test should take maybe 1.5 hours?
> 
> I meet the hang issue too with your improve-python-selftest branch, while I can not fix it because I do not understand the test suite now.
> 
> 

What Distribution/kernel version are you running?

> I have following advises which might make these tests better:
> 
> simulate iscsi target with tools such as tgtadm so that the tests can run within a single device. tgtadm commands like following is helpful:
> tgtadm --lld iscsi --mode target --op new --tid 1 --targetname iqn.xxx.xxxx
> tgtadm --lld iscsi --mode logicalunit --op new --tid 1 --lun 1 --backing-store xxx
> tgtadm --lld iscsi --mode target --op bind --tid 1 --initiator-address ALL

I never use tgt any more for iSCSI targets — I much prefer the ease of use in targetcli/LIO.

But I’m beginning to think the initiator and target should be on separate systems, so that the target code doesn’t effect the initiator code.

> It takes too long to run these cases, we might splict to two kind of jobs: heavyweight and lightweight. For heavyweight tests, run all test cases, we do not care how long it takes. For lightweight tests, make sure it can finish fastly, maybe we can exclude bonnie++ and fio tests from the lightweight tests.
> 
> 
> Extent the coverage to more core scenario, such as CHAP.
> 
> —
> 


Please see the TODO file, which already lists some suggested improvements. The current tests are a clone of what was in regression.sh, so no new functionality testing was added. But it’d be a great place to add some more.

If you need help understanding the tests, let me know. You can use debug mode to see what is happening when an error occurs. If you need any help understanding anything about the tests, let me know. The README is quite detailed now. :)

— 
Lee

**Comment by wenchao-hao** [comment] 2022-03-01 17:29
> What Distribution/kernel version are you running?

I am runnig 4.19 kernel which is CentOS-based distro.

> I never use tgt any more for iSCSI targets — I much prefer the ease of use in targetcli/LIO. But I’m beginning to think the initiator and target should be on separate systems, so that the target code doesn’t effect the initiator code.

If the initiator and target are on separate systems, the regression tests can not be run automaticly(like make check or make test of most packages)

> If you need help understanding the tests, let me know. You can use debug mode to see what is happening when an error occurs. If you need any help understanding anything about the tests, let me know. The README is quite detailed now. :)

Yes, I am now running with -d option. I need your help about how to add test case in the future.

**Comment by gonzoleeman** [comment] 2022-03-01 17:33
On Mar 1, 2022, at 9:29 AM, Wenchao Hao ***@***.***> wrote:
> 
> 
> What Distribution/kernel version are you running?
> 
> I am runnig 4.19 kernel which is CentOS-based distro.
> 
> 

A newer kernel would likely do better. Mike Christie has made several improvements in the inintiator and target code since then.

> I never use tgt any more for iSCSI targets — I much prefer the ease of use in targetcli/LIO. But I’m beginning to think the initiator and target should be on separate systems, so that the target code doesn’t effect the initiator code.
> 
> If the initiator and target are on separate systems, the regression tests can not be run automaticly(like make check or make test of most packages)
> 
> 

They already can’t be run automatically now. And having the ability to connect to targets either locally or remotely should be part of the testing IMHO. Especially in older kernels (like yours).
> If you need help understanding the tests, let me know. You can use debug mode to see what is happening when an error occurs. If you need any help understanding anything about the tests, let me know. The README is quite detailed now. :)
> 
> Yes, I am now running with -d option. I need your help about how to add test case in the future.
> 
> 

No problem. This is all based on the python unittest package. But if you don’t know/love python it might appear a bit intimidating. Just let me know.

— 
Lee D

**Comment by wenchao-hao** [comment] 2022-03-02 15:49
> I just merged these changes (with updated commit messages) to master. I will leave the initial branch you are using, for now (called "improve-python-selftest"), but it will be removed soon. But all the changes are now in master.

I checked out the master branch and run the tests successfully. While I still want to make these tests able to run automatic without a second system, so I wrote a shell script, the script would deploy an iSCSI target locally, login it, then call python to run your test. I want to push it to test directory， do you think it's ok? The shell script is like following:

```
TARGET_IP=127.0.0.1                                                                                                                                           
TARGET_NAME=$(iscsi-iname)                                                                                                                                    
INITIATOR_NAME=$(cat /etc/iscsi/initiatorname.iscsi | awk -F = '{print$2}')                                                                                   
                                                                                                                                                              
dd if=/dev/zero of=/var/tmp/fileio.img bs=1M count=1024                                                                                                       

############################ create iscsi target ###################################
echo -e "cd /backstores/fileio\n" | targetcli
echo -e "create fileio0 /var/tmp/fileio.img\n" | targetcli
echo -e "cd /iscsi\n" | targetcli
echo -e "create $TARGET_NAME\n" | targetcli
echo -e "cd /iscsi/$TARGET_NAME/tpg1/luns\n" | targetcli
echo -e "create /backstores/fileio/fileio0\n" | targetcli
echo -e "cd /iscsi/$TARGET_NAME/tpg1/acls\n" | targetcli
echo -e "create $INITIATOR_NAME\n" | targetcli

iscsiadm -m discovery -t st -p 127.0.0.1
iscsiadm -m node -p 127.0.0.1 -l || exit 0
DISK_NAME=$(iscsiadm -m session -P 3 | grep "Attached scsi disk" | awk '{print $4}')

############################ run testcases ###################################
/usr/bin/python3 test-open-iscsi.py -v -f -t $TARGET_NAME -i $TARGET_IP -D /dev/$DISK_NAME

iscsiadm -m node -p $TARGET_IP -u
iscsiadm -m node -p $TARGET_IP -o delete

########################### delete iscsi target ###################################
echo -e "cd /iscsi\n" | targetcli
echo -e "delete $TARGET_NAME\n" | targetcli
echo -e "cd /backstores/fileio\n" | targetcli
echo -e "delete fileio0\n" | targetcli

rm /var/tmp/fileio.img
```

**Comment by gonzoleeman** [comment] 2022-03-02 18:59
> > Also, FWIW, I've noticed a problem running some tests with 512-byte block size. I'm trying to run all 960 tests, to see how long that takes, but the system pretty consistently hangs. Right now, I'm running all tests using a single blocksize, one block size at a time. Each block size test should take maybe 1.5 hours?
> 
> I meet the hang issue too with your branch `improve-python-selftest`, while I can not fix it because I do not understand the test suite now.

I find I do not get this issue if I (1) run on a newer kernel (I'm now testing using openSUSE Tumbleweed with 5.16.11 kernel), and (2) I have the initiator and target on different systems. (Remember, I was using the LIO/kernel target).

> 
> I have following advises which might make these tests better:
> 
>     1. simulate iscsi target with tools such as `tgtadm` so that the tests can run within a single device. `tgtadm` commands like following is helpful:
> 
> 
> ```
> tgtadm --lld iscsi --mode target --op new --tid 1 --targetname iqn.xxx.xxxx
> tgtadm --lld iscsi --mode logicalunit --op new --tid 1 --lun 1 --backing-store xxx
> tgtadm --lld iscsi --mode target --op bind --tid 1 --initiator-address ALL
> ```

I have no objection to suggesting this as a possible usage in the test README. some users may prefer this over rolling their own target.

> 
>     2. It takes too long to run these cases, we might splict to two kind of jobs: heavyweight and lightweight. For heavyweight tests, run all test cases, we do not care how long it takes. For  lightweight tests, make sure it can finish fastly, maybe we can exclude bonnie++ and fio tests from the lightweight tests.

Please see the TODO file. :)

> 
>     3. Extent the coverage to more core scenario, such as CHAP.

Again, in the TODO file already.

**Comment by gonzoleeman** [comment] 2022-03-02 19:05
> > I just merged these changes (with updated commit messages) to master. I will leave the initial branch you are using, for now (called "improve-python-selftest"), but it will be removed soon. But all the changes are now in master.
> 
> I checked out the master branch and run the tests successfully. 

Excellent

> While I still want to make these tests able to run automatic without a second system, so I wrote a shell script, the script would deploy an iSCSI target locally, login it, then call python to run your test. I want to push it to test directory， do you think it's ok? The shell script is like following:
> 
> ```
> 

I think adding this to the test subdirectory is fine, as an example. But there is no way the default test is going to do this. I specifically want to be able to control my target manually. Right now I have found that running the target and initiator on the same system can be problematic, at least with the LIO/targetcli target. I have not tested with tgtadm -- perhaps it's better, since it does more in user-space. But even so it bogs down my system to have both ends of the test there.

I wouldn't mind seeing a _version_ of the test that (1) runs more quickly, and (2) sets up and tears down the target for me. This would be great perhaps as an addition to the Linux block tests, as a quick sanity test.

Perhaps your script should go in an "examples" subdirectory under test? And you could add a note in the README (or I could) that suggests looking at examples in that directory.

I think the "how can I run test cases" issue is complete. But I'll leave this issue open for now, until commenting runs its course.

**Comment by wenchao-hao** [comment] 2022-03-03 15:35
> Perhaps your script should go in an "examples" subdirectory under test? And you could add a note in the README (or I could) that suggests looking at examples in that directory.

OK, I would run this scripts on more system and make a PR when it runs more stable. For next step, I might make some PRs to deal with what list in TODO.

**Comment by gonzoleeman** [comment] 2022-03-03 17:20
Closing this issue since tests can be run now.

**Closed by gonzoleeman** 2022-03-03 17:20 UTC
