### ISSUE TITLE
How queued_cmdsn changed in libiscsi?

### ISSUE THREAD

**Issue by N07ME** [open-iscsi/open-iscsi#430] opened 2023-11-20 06:23 UTC
Hi I met a problem that host queuecommand failed to a target,and it seemed to be related with cmdsn

The syslog prints as below:
iscsi_check_cmdsn_window_closed iSCSI CmdSN closed. ExpCmdSn 2147483626 MaxCmdSN 0 CmdSN 2147483626/2147483626

The enviroment I use:
kernel version:4.14.131 x86_64

Function iscsi_check_cmdsn_window_closed shows that queued_cmdsn in an iscsi session should never be larger than max_cmdsn,or queuecommand may fail.But I've searched through all the kernel code,I only saw that queued_cmdsn may increase after a scsi command or a mgmt task success,and decrease if a cmd failed,and it may be refreshed in a session start.

I also did some survey about this.According to iscsi protocol(I refer to it on https://www.ietf.org/rfc/rfc3720.txt),I knew that when the target return a scsi response to the initiator,the initiator need refresh its max_cmdsn in this session(may be in function __iscsi_update_cmdsn).

And my problem is,when should queued_cmdsn change in initiator node?

If the max_cmdsn from target response changed,or it exceeds u32 and turn to 0,how should  the initiator do with queued_cmdsn to make it catch up with new max_cmdsn?

**Comment by mikechristie** [comment] 2023-11-20 22:13
Ignoring the places where we decrement or reset the sequence numbers because of error handling, they normally just increase. When they roll over the functions like iscsi_sna_lte are supposed to handle that (check out https://datatracker.ietf.org/doc/html/rfc1982 for details on that).

Note that it's normal to hit see the window closed when you are sending a lot of IOs. The target may take in N commands, and the window is closed until it handles them. When it completes some commands, then it opens it up.

**Comment by N07ME** [comment] 2023-11-21 02:15
@mikechristie Thanks for reply.

I checked the code again and ensured that queued_cmdsn may be increased before iscsi_queuecommand return success

```
        session->queued_cmdsn++;
	spin_unlock_bh(&session->frwd_lock);
	return 0;

prepd_reject:
	spin_lock_bh(&session->back_lock);
	iscsi_complete_task(task, ISCSI_TASK_REQUEUE_SCSIQ);
	spin_unlock_bh(&session->back_lock);
reject:
	spin_unlock_bh(&session->frwd_lock);
	ISCSI_DBG_SESSION(session, "cmd 0x%x rejected (%d)\n",
			  sc->cmnd[0], reason);
	return SCSI_MLQUEUE_TARGET_BUSY;
```

And if iscsi_check_cmdsn_window_closed failed,it just goes to reject,queued_cmdsn left unchanged.
```
	if (iscsi_check_cmdsn_window_closed(conn)) {
		reason = FAILURE_WINDOW_CLOSED;
		goto reject;
	}
```

> Note that it's normal to hit see the window closed when you are sending a lot of IOs. The target may take in N commands, and the window is closed until it handles them. When it completes some commands, then it opens it up.

As what I see,once iscsi_check_cmdsn_window_closed failed and window is closed,then queued_cmdsn can be increased nowhere,and commands followed will all be checked failed because they can never be over max_cmdsn.

It really bothers me a lot since both max_cmdsn and queued_cmdsn are u32 type so it seems roll over can happen easily.

**Comment by mikechristie** [comment] 2023-11-21 17:05
> @mikechristie Thanks for reply.
> 
> I checked the code again and ensured that queued_cmdsn may be increased before iscsi_queuecommand return success
> 
> ```
>         session->queued_cmdsn++;
> 	spin_unlock_bh(&session->frwd_lock);
> 	return 0;
> 
> prepd_reject:
> 	spin_lock_bh(&session->back_lock);
> 	iscsi_complete_task(task, ISCSI_TASK_REQUEUE_SCSIQ);
> 	spin_unlock_bh(&session->back_lock);
> reject:
> 	spin_unlock_bh(&session->frwd_lock);
> 	ISCSI_DBG_SESSION(session, "cmd 0x%x rejected (%d)\n",
> 			  sc->cmnd[0], reason);
> 	return SCSI_MLQUEUE_TARGET_BUSY;
> ```
> 
> And if iscsi_check_cmdsn_window_closed failed,it just goes to reject,queued_cmdsn left unchanged.

I don't see the issue you are trying to describe.


> 
> ```
> 	if (iscsi_check_cmdsn_window_closed(conn)) {
> 		reason = FAILURE_WINDOW_CLOSED;
> 		goto reject;
> 	}
> ```
> 
> > Note that it's normal to hit see the window closed when you are sending a lot of IOs. The target may take in N commands, and the window is closed until it handles them. When it completes some commands, then it opens it up.
> 
> As what I see,once iscsi_check_cmdsn_window_closed failed and window is closed,then queued_cmdsn can be increased nowhere,and commands followed will all be checked failed because they can never be over max_cmdsn.

I'm not sure what the issue is.

Here is a simplified version of what happens:

The target's window will be 32 commands (Let's just say queued_cmdsn = 1 and max_cmdsn = 33 so 33 - 1 = 32). We send it 32 commands, and so on 33 we see the window is now closed (queued_cmdsn now equals max_cmdsn).

When the target completes a command, it increases the max_cmdsn value. When that happens the iscsi/scsi layer run iscsi_queuecommand again. This time we see max_cmdsn is now +1, so we can take in another command and increase qeuued_cmdsn. We then might try to run iscsi_queuecommand again, but again queued_cmdsn will have hit max_cmdsn. When the target completes a command again though, then we repeat and execute another command.

What happens if there are no commands? Then the target can send a nop to us with a increased max_cmdsn and we will see the window open again.


> 
> It really bothers me a lot since both max_cmdsn and queued_cmdsn are u32 type so it seems roll over can happen easily.

But what is the issue if it rolls over. Is there a specific case that we are hitting a bug for? Does iscsi_sna_lte not handle that correctly?

It sounds like you have some guesses but not an exact failure case. I'm going to close this for now, because I can't spend time debugging something that doesn't have a specific bug :)

When you have a specific case, then please re-open with the details like what iscsi target you are using, IO workload, debugging output, what exactly you are seeing (like does IO hang forver) and we can debug it together.

**Closed by mikechristie** 2023-11-21 17:05 UTC
