### ISSUE TITLE
Race condition between access & mkdir

### ISSUE THREAD

**Issue by tasleson** [open-iscsi/open-iscsi#95] opened 2018-03-22 17:54 UTC
From the time it takes you to get the result of `access` to when you do the `mkdir`, the state of the FS may have changed.  Suggest alternative implementations which don't suffer from this.
``` C
int idbm_lock(void)
{
        int fd, i, ret;

        if (db->refs > 0) {
                db->refs++;
                return 0;
        }

        if (access(LOCK_DIR, F_OK) != 0) {
                if (mkdir(LOCK_DIR, 0660) != 0) {
                        log_error("Could not open %s: %s", LOCK_DIR,
                                  strerror(errno));
                        return ISCSI_ERR_IDBM;
                }
        }
...
```

**Comment by gonzoleeman** [comment] 2018-04-13 00:08
Please submit a pull request / patch (if not already done).

**Comment by gonzoleeman** [comment] 2019-02-12 22:30
Marking as resolved since a pull request has been merged.

**Comment by uberjay** [comment] 2024-05-16 18:41
The associated pull request did not fix this issue (it was merely mentioned in a PR comment that this issue was filed for tracking purposes). The access/mkdir race still exists!

**Comment by gonzoleeman** [comment] 2024-05-16 21:05
I'm not sure what you want here, but re-opening.

Please describe the scenario where an error can occur? Are you running two iscsid daemons? If not, then who is creating the lock directory between the time access() says it's not there and we do the mkdir()?

It seems like one solution to this not-really-a-problem would be to check access() again if mkdir fails with EEXIST. Do you have a better suggestion? I believe I asked for a pull request and never got one ...

**Comment by gonzoleeman** [comment] 2024-05-17 16:59
Note: there are at least half a dozen other places in open-iscsi where it does the access()/mkdir() sequence, not just for the lock directory.

**Comment by uberjay** [comment] 2024-05-17 18:50
The lock directory is in place to synchronize access by concurrent executions of `iscsiadm` -- if everything on disk were only read and written from iscsid, presumably there wouldn't be a need for a lock directory (as there would only be one process interacting with the on-disk state).

I don't know about any of the other access/mkdir sequenecs, but I presume they could be safe, as (maybe???) they are only done after acquiring the idbm lock? I'm not sure, as the only one I've seen occur is the lock directory.

To reproduce it, remove the lock directory and execute 2 concurrent iscsiadm commands which would need access to the on-disk iscsi state:

```
[root@localhost ~]# rm -rf /var/lock/iscsi
[root@localhost ~]# iscsiadm -m node & iscsiadm -m node
[1] 12629
iscsiadm: Could not open /var/lock/iscsi: File exists
172.16.100.7:3261,1 xxxx
iscsiadm: Could not execute operation on all records: encountered iSCSI database failure
[1]+  Done                    iscsiadm -m node
```

For this sort of TOCTTOU (time-of-check to time-of-use) bug, the best solution is typically to issue the `mkdir` and treat `EEXIST` as success.

**Comment by uberjay** [comment] 2024-05-22 18:18
> So isn't the point of the DB lock to ensure that only one iscsiadm has control of the Database at any one time? If so, why would we want the second iscsiadm to succeed?
> 
> 
> 
> We don't really have the concept of read-only vs read-write access to the DB, so we must assume that any new client of the DB may want to modify it. We can't have concurrent modification.
> 
> 
> 
> It seems like we would need some form of more find-grained locking to enable two different "iscsiadm -m node" commands to execute "simultaneously".

This is just to create the directory, not the lock file.

**Comment by gonzoleeman** [comment] 2024-05-22 19:02
Well, this lock does serialize access, but it also makes the loser wait up to 10 sec x 3000 tries! (500 minutes, or about 8 hours!).

I have pushed a new branch:  gonzoleeman/open-iscsi#safe-lock-dir-creation

Can you try it out? I can't reproduce the error your seeing doing this, on my system:

# iscsiadm -m node & iscsiadm -m node

So I can't verify that my changes fix it.

**Comment by uberjay** [comment] 2024-05-22 19:06
Did you remove the lock directory before executing the concurrent iscsiadm commands? (If not, the directory almost certainly already exists, so no mkdir race can possibly occur...)

**Comment by gonzoleeman** [comment] 2024-05-22 19:16
> Did you remove the lock directory before executing the concurrent iscsiadm commands? (If not, the directory almost certainly already exists, so no mkdir race can possibly occur...)

LOL. So it's even harder than I thought to trigger this issue. It has to be the very first time you run iscsiadm.

Nevertheless, I found some other small issues in the code, not to mention there are two version of it, and it's not immediately clear to me why. (The library code was added by an eager person from RH a while ago, who isn't around much any longer, or I'd ask him why there's so much duplication.)

I tested as you suggested, and sure enough my change seems to fix this issue. I'll file a pull request and give others a chance to comment before I merge it.

**Comment by cleech** [comment] 2024-05-22 19:17
I seem to remember dealing with this, but maybe I'm thinking of a different project.  Access checks are often flawed, as the file-system state can change between them and the next syscall.

I think something like this is might be wanted ?

```
diff --git a/libopeniscsiusr/idbm.c b/libopeniscsiusr/idbm.c
index 6f15d1a..e19b9be 100644
--- a/libopeniscsiusr/idbm.c
+++ b/libopeniscsiusr/idbm.c
@@ -320,12 +320,11 @@ int _idbm_lock(struct iscsi_context *ctx)
                return 0;
        }
 
-       if (access(LOCK_DIR, F_OK) != 0) {
-               if (mkdir(LOCK_DIR, 0770) != 0) {
-                       _error(ctx, "Could not open %s: %d %s", LOCK_DIR, errno,
-                               _strerror(errno, strerr_buff));
-                       return LIBISCSI_ERR_IDBM;
-               }
+       if (((mkdir(LOCK_DIR, 0770) != 0) && (errno != EEXIST)) ||
+           (access(LOCK_DIR, F_OK) != 0)) {
+               _error(ctx, "Could not open %s: %d %s", LOCK_DIR, errno,
+                       _strerror(errno, strerr_buff));
+               return LIBISCSI_ERR_IDBM;
        }
 
        fd = open(LOCK_FILE, O_RDWR | O_CREAT, 0666);
diff --git a/usr/idbm.c b/usr/idbm.c
index 18ae881..0f884b8 100644
--- a/usr/idbm.c
+++ b/usr/idbm.c
@@ -1444,12 +1444,10 @@ int idbm_lock(void)
                return 0;
        }
 
-       if (access(LOCK_DIR, F_OK) != 0) {
-               if (mkdir(LOCK_DIR, 0770) != 0) {
-                       log_error("Could not open %s: %s", LOCK_DIR,
-                                 strerror(errno));
-                       return ISCSI_ERR_IDBM;
-               }
+       if (((mkdir(LOCK_DIR, 0770) != 0) && (errno != EEXIST)) ||
+           (access(LOCK_DIR, F_OK) != 0)) {
+               log_error("Could not open %s: %s", LOCK_DIR, strerror(errno));
+               return ISCSI_ERR_IDBM;
        }
 
        fd = open(LOCK_FILE, O_RDWR | O_CREAT, 0666);

```

**Comment by uberjay** [comment] 2024-05-22 19:19
Yeah, I hear you that it feels a little silly! 😅However, we regularly ran into this with automated testing, before adding a workaround. I agree that it’s not a critical issue, but it sure is annoying and doesn’t need to be!On May 22, 2024, at 15:16, Lee Duncan ***@***.***> wrote:﻿

Did you remove the lock directory before executing the concurrent iscsiadm commands? (If not, the directory almost certainly already exists, so no mkdir race can possibly occur...)

LOL. So it's even harder than I thought to trigger this issue. It has to be the very first time you run iscsiadm.
Nevertheless, I found some other small issues in the code, not to mention there are two version of it, and it's not immediately clear to me why. (The library code was added by an eager person from RH a while ago, who isn't around much any longer, or I'd ask him why there's so much duplication.)
I tested as you suggested, and sure enough my change seems to fix this issue. I'll file a pull request and give others a chance to comment before I merge it.

**Comment by gonzoleeman** [comment] 2024-05-22 19:20
> I seem to remember dealing with this, but maybe I'm thinking of a different project. Access checks are often flawed, as the file-system state can change between them and the next syscall.
> 
> I think something like this is might be wanted ?
> 
> ```
> diff --git a/libopeniscsiusr/idbm.c b/libopeniscsiusr/idbm.c
> index 6f15d1a..e19b9be 100644
> --- a/libopeniscsiusr/idbm.c
> +++ b/libopeniscsiusr/idbm.c
> @@ -320,12 +320,11 @@ int _idbm_lock(struct iscsi_context *ctx)
>                 return 0;
>         }
>  
> -       if (access(LOCK_DIR, F_OK) != 0) {
> -               if (mkdir(LOCK_DIR, 0770) != 0) {
> -                       _error(ctx, "Could not open %s: %d %s", LOCK_DIR, errno,
> -                               _strerror(errno, strerr_buff));
> -                       return LIBISCSI_ERR_IDBM;
> -               }
> +       if (((mkdir(LOCK_DIR, 0770) != 0) && (errno != EEXIST)) ||
> +           (access(LOCK_DIR, F_OK) != 0)) {
> +               _error(ctx, "Could not open %s: %d %s", LOCK_DIR, errno,
> +                       _strerror(errno, strerr_buff));
> +               return LIBISCSI_ERR_IDBM;
>         }
>  
>         fd = open(LOCK_FILE, O_RDWR | O_CREAT, 0666);
> diff --git a/usr/idbm.c b/usr/idbm.c
> index 18ae881..0f884b8 100644
> --- a/usr/idbm.c
> +++ b/usr/idbm.c
> @@ -1444,12 +1444,10 @@ int idbm_lock(void)
>                 return 0;
>         }
>  
> -       if (access(LOCK_DIR, F_OK) != 0) {
> -               if (mkdir(LOCK_DIR, 0770) != 0) {
> -                       log_error("Could not open %s: %s", LOCK_DIR,
> -                                 strerror(errno));
> -                       return ISCSI_ERR_IDBM;
> -               }
> +       if (((mkdir(LOCK_DIR, 0770) != 0) && (errno != EEXIST)) ||
> +           (access(LOCK_DIR, F_OK) != 0)) {
> +               log_error("Could not open %s: %s", LOCK_DIR, strerror(errno));
> +               return ISCSI_ERR_IDBM;
>         }
>  
>         fd = open(LOCK_FILE, O_RDWR | O_CREAT, 0666);
> ```

Yes, that would work too. Please see my pull request.

**Comment by cleech** [comment] 2024-05-22 19:36
Hmm, access is only being used to check for existence and not any other permissions.  So I guess we don't need to worry about mkdir returning EEXIST but not being able to write the lock file, we just let open fail in that case?  Is access needed at all then, or should this just always attempt mkdir and accept EEXIST?

I'll take a look at the other changes in your PR

**Comment by gonzoleeman** [comment] 2024-05-22 21:04
On May 22, 2024, at 12:37 PM, Chris Leech ***@***.***> wrote:
> 
> 
> Hmm, access is only being used to check for existence and not any other permissions. So I guess we don't need to worry about mkdir returning EEXIST but not being able to write the lock file, we just let open fail in that case? Is access needed at all then, or should this just always attempt mkdir and accept EEXIST?
> 

It just seems wrong to mkdir() if the directory exists, since normally it will exist (all but the first time?). But I’m not actually sure that a usually-failing mkdir() is less efficient than calling access() every time.

And the “acess()/mkdir()” sequence is in at least 5 other places in the project, though the other places don’t seem to suffer the same race condition, perhaps because they are used inside the DB lock?
> I'll take a look at the other changes in your PR
> 
Cool.

I really hate that this code is in two places. The library was supposed to eliminate duplication. :(

Great project for an intern: further reduce duplication between lthe library and the rest of the code.

— 
Lee

**Comment by gonzoleeman** [comment] 2024-05-23 18:39
Closing this issue, since I've merged the proposed changes.

**Closed by gonzoleeman** 2024-05-23 18:39 UTC

**Comment by uberjay** [comment] 2024-05-24 03:44
Thank you! I know it's not a glamorous change, but it's appreciated!
