### ISSUE TITLE
Login/Text in progress. Cannot start new task

### ISSUE THREAD

**Issue by happyzyz** [open-iscsi/open-iscsi#424] opened 2023-08-16 10:11 UTC
![image](https://github.com/open-iscsi/open-iscsi/assets/123857360/07a5b052-32e9-45e7-953f-7a26f4e00efe)

![image](https://github.com/open-iscsi/open-iscsi/assets/123857360/c636e0cc-539f-430c-b816-1e878830c4dd)

Hi iscsi experts, 
I am encountering some failures of login : "Login/Text in progress. Cannot start new task "
Any feedback will be appreciated. Thanks!

**Comment by happyzyz** [comment] 2023-08-16 11:04
These two images were obtained using the tool bpftrace：
![image](https://github.com/open-iscsi/open-iscsi/assets/123857360/21c96c49-17f5-4eeb-b638-60bd186cf428)
![企业微信截图_16921799839157](https://github.com/open-iscsi/open-iscsi/assets/123857360/b9b03699-a546-4873-89e8-be6cdaa2edb9)
the state : conn->login_task->state;
the refcnt: conn->login_task->refcount （This is abnormal）;

**Comment by gonzoleeman** [comment] 2023-08-16 15:36
On Aug 16, 2023, at 3:11 AM, happyzyz ***@***.***> wrote:
> 
> 
>  <https://user-images.githubusercontent.com/123857360/260976028-07a5b052-32e9-45e7-953f-7a26f4e00efe.png>
>  <https://user-images.githubusercontent.com/123857360/260975822-c636e0cc-539f-430c-b816-1e878830c4dd.png>
> Hi iscsi experts,
> I am encountering some failures of login : "Login/Text in progress. Cannot start new task "
> Any feedback will be appreciated. Thanks!
> 

What are you doing when this happens?

What target(s) are you trying to connect to? Connection 516? What exactly is happening?

— 
Lee Duncan

**Comment by happyzyz** [comment] 2023-08-17 03:08
I did some operations, such as stopping target, restarting iscsid, starting target, and so on. Then this situation arose.
![image](https://github.com/open-iscsi/open-iscsi/assets/123857360/82b59731-ad4f-485f-8fb7-aff1a1ca92d4)

**Comment by gonzoleeman** [comment] 2023-08-17 14:14
On Aug 16, 2023, at 8:09 PM, happyzyz ***@***.***> wrote:
> 
> 
> I did some operations, such as stopping target, restarting iscsid, starting target, and so on. Then this situation arose.
>  <https://user-images.githubusercontent.com/123857360/261185719-82b59731-ad4f-485f-8fb7-aff1a1ca92d4.png>
There is no way to try to address this without more information.

What targets are you using? Hardware, or software? Did you set them up? It looks like you have lots of targets. How many? It looks like they are on different IP addresses?

What exact sequence did you follow on your open-iscsi initiator system? For example:
- booted system with no targets and iscsi not running?
- what systemd services do you have enabled for iscsi?
- discovered targets (how?) — now did you node database get populated?
- logged into targets (using systemd service?)
- you say you “stopped” the targets? How do you do that, and why would you do that when you are connected to them?
- and you restarted iscsid when targets where “stopped”?
- what kind of timing? i.e. are you doing this rapidly, or lots of time between steps?

Even if you have 10 targets, you must have disconnected and reconnected 50 times to get up to connection numbers like you have. Please be specific.

Also, have you filed a bug with your distro? What distro/version are you using?

If you want free help from the open-iscsi community, you have to supply more info.
— 
Lee Duncan

**Comment by happyzyz** [comment] 2023-08-28 02:02
I'm sorry for taking a long time to reply to you.
I can't remember all the operations I did, there was a lot of time between the steps, but I remember that when the problem occurred, the target and were normal (based on spdk) and the iscsid service was started.
I discovered and logged into the target using iscsiadm, and it was normal before these steps.
 The operating system has now restarted and valid information cannot be found. If it comes out again next time, I will provide additional information
Thank you again for your reply

**Comment by gonzoleeman** [comment] 2023-11-04 18:02
I will close this issue, since you can't reproduce it (nor can I). Please re-open or open a new issue if it occurs again. I will need to know kernel version and distro, open-iscsi version, target type/name, and steps you took before the problem occurs.

**Closed by gonzoleeman** 2023-11-04 18:02 UTC
