### ISSUE TITLE
iscsiadm hangs and tcpdump shows nothing

### ISSUE THREAD

**Issue by jprukner** [open-iscsi/open-iscsi#166] opened 2019-05-15 07:21 UTC
I am troubleshooting `iscsiadm`. 
```
iscsiadm --mode discovery --portal 10.144.35.235 --type sendtargets --discover
```
The command mentioned above blocks and does nothing. I've cleared ipvs and iptables.
```
ipvsadm -C && iptables --flush
```
When I run `tcpdump`, no packets are shown.
```
root@master:~# tcpdump host 10.144.35.235
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp0s20f0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel
1 packet dropped by interface
```

Some config:
```
root@master:~# cat /etc/iscsi/initiatorname.iscsi
InitiatorName=iqn.2019-05.net.packet:device.7670d17c
```
`/etc/iscsi/iscsid.conf` - https://pastebin.com/ZGcwNbBP

`/etc/multipath.conf` - https://pastebin.com/NEFeM1nf

```
root@master:~# iscsiadm --version
iscsiadm version 2.0-874
```
Using Ubuntu 18.04.

Could it be related to https://github.com/open-iscsi/open-iscsi/issues/155? @gonzoleeman

**Comment by gonzoleeman** [comment] 2019-05-16 16:57
> Could it be related to #155? @gonzoleeman

There's an easy way to check: please try the patch from #155 or just get the latest upstream sources and try them, as the fix for that issue has already been merged.

Note: adding "--discover" is redundant when running "iscsiadm -m discovery -t st -p PORTAL", as it is only needed if using the discoverydb mode, i..e "iscsiadm -m discoverydb -t st -p PORTAL --discover"

**Comment by gonzoleeman** [comment] 2019-05-16 16:58
It certainly looks like (1) your root issue is that there's a problem with your network configuration, and (2) perhaps you're hitting and iscsid issue where it mishandles such an error condition.

**Comment by jprukner** [comment] 2019-05-16 17:44
> There's an easy way to check: please try the patch from #155 or just get the latest upstream sources and try them, as the fix for that issue has already been merged.

@gonzoleeman Thanks for a suggestion, I will try it and let you know.

> It certainly looks like (1) your root issue is that there's a problem with your network configuration, and (2) perhaps you're hitting and iscsid issue where it mishandles such an error condition.

I guess if the network configuration was off, the mentioned command would hang for all cases. It only happens on volumes that are created by [csi-packet](https://github.com/packethost/csi-packet). The automatic mounting fails because [this function](https://github.com/packethost/csi-packet/blob/6f094de5d280183efd9b1f7195bf2e3a08aa14ee/pkg/driver/attacher.go#L89) blocks. For volumes created by hand, it works just fine. What do you think? @gonzoleeman

**Comment by jprukner** [comment] 2019-05-17 16:45
I have cloned the master branch. ran `make` and `make install`. Still the same issue.
`iscsiadm --mode discovery --portal 10.144.34.130 --type sendtargets` still hangs. Any ideas? @gonzoleeman

**Comment by jprukner** [comment] 2019-05-17 16:59
Ok, so I enabled debug.
```
root@master:~# iscsiadm --mode discovery --portal 10.144.34.130 --type sendtargets -d 8
iscsiadm: Max file limits 1024 1048576
iscsiadm: Could not get config file for sync config
iscsiadm: Looking for config file /etc/iscsi/send_targets/10.144.34.130,3260
iscsiadm: Looking for config file /etc/iscsi/send_targets/10.144.34.130,3260 config st_config.
iscsiadm: updated 'discovery.startup', 'manual' => 'manual'
iscsiadm: updated 'discovery.type', 'sendtargets' => 'sendtargets'
iscsiadm: updated 'discovery.sendtargets.address', '' => '10.144.34.130'
iscsiadm: updated 'discovery.sendtargets.port', '0' => '3260'
iscsiadm: updated 'discovery.sendtargets.auth.authmethod', 'None' => 'None'
iscsiadm: updated 'discovery.sendtargets.timeo.login_timeout', '15' => '15'
iscsiadm: updated 'discovery.sendtargets.use_discoveryd', 'No' => 'No'
iscsiadm: updated 'discovery.sendtargets.discoveryd_poll_inval', '30' => '30'
iscsiadm: updated 'discovery.sendtargets.reopen_max', '5' => '5'
iscsiadm: updated 'discovery.sendtargets.timeo.auth_timeout', '45' => '45'
iscsiadm: updated 'discovery.sendtargets.timeo.active_timeout', '30' => '30'
iscsiadm: updated 'discovery.sendtargets.iscsi.MaxRecvDataSegmentLength', '32768' => '32768'
iscsiadm: disc rec already exists
iscsiadm: Looking for config file /etc/iscsi/send_targets/10.144.34.130,3260
iscsiadm: iface_for_each_iface found iface.example
iscsiadm: looking for iface conf /etc/iscsi/ifaces/iface.example
iscsiadm: iface is not valid Iface settings [hw=,ip=,net_if=,iscsi_if=iface.example]
iscsiadm: starting sendtargets discovery, address 10.144.34.130:3260, 
iscsiadm: in read_transports
iscsiadm: Adding new transport iser
iscsiadm: Matched transport iser
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_transport/iser'/'handle'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_transport/iser'/'caps'
iscsiadm: Adding new transport tcp
iscsiadm: Matched transport tcp
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_transport/tcp'/'handle'
iscsiadm: sysfs_attr_get_value: open '/class/iscsi_transport/tcp'/'caps'
```
After above is printed, the command hangs.

**Comment by gonzoleeman** [comment] 2019-05-17 17:53
Interesting. Obviously your csi plugin is causing a problem, but the question is what problem is that!?

Can you have iscsid running with "-d8" and capture the log messages file when this hang occurs? I'm interested in what happens between the discovery request and the hang, and I can't reproduce this myself, since I'm not planning to set up a kubernetes deployment any time soon.

**Comment by jprukner** [comment] 2019-05-17 19:00
Well, the hang is not visible that much in logs. There are bunch of lines with the same time - start of `iscsid` - and then one line with time related to the hang. After that first hang, no matter how many times I run the command, no other log lines are being shown in `journalctl -u iscsid`. 
```
...
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.iscsi.MaxRecvDataSegmentLength', '32768' => '32768'
May 17 18:42:53 master iscsid[11173]: st_start 10.144.51.159:3260 0
May 17 18:42:53 master iscsid[11173]: found 10.144.51.100,3260
May 17 18:42:53 master iscsid[11173]: Looking for config file /etc/iscsi/send_targets/10.144.51.100,3260
May 17 18:42:53 master iscsid[11173]: Looking for config file /etc/iscsi/send_targets/10.144.51.100,3260 config st_config.
May 17 18:42:53 master iscsid[11173]: updated 'discovery.startup', 'manual' => 'manual'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.type', 'sendtargets' => 'sendtargets'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.address', '' => '10.144.51.100'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.port', '0' => '3260'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.auth.authmethod', 'None' => 'None'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.timeo.login_timeout', '15' => '15'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.use_discoveryd', 'No' => 'No'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.discoveryd_poll_inval', '30' => '30'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.reopen_max', '5' => '5'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.timeo.auth_timeout', '45' => '45'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.timeo.active_timeout', '30' => '30'
May 17 18:42:53 master iscsid[11173]: updated 'discovery.sendtargets.iscsi.MaxRecvDataSegmentLength', '32768' => '32768'
May 17 18:42:53 master iscsid[11173]: st_start 10.144.51.100:3260 0
May 17 18:42:53 master iscsid[11173]: current time 1117
May 17 18:42:53 master iscsid[11173]: nothing on pend_list, deactivating alarm
May 17 18:47:47 master iscsid[11173]: poll result 1
```

**Comment by jprukner** [comment] 2019-05-18 06:56
So, I forgot to update image of csi plugin with latest iscsiadm yesterday :( Now, the discovery command does not hang, but fails on creating filesystem. But I guess it is not subject of this issue.

**Closed** 2019-05-18 06:57 UTC
