### ISSUE TITLE
CHAP MD5 with Synology DS no longer works in 2.1.0

### ISSUE THREAD

**Issue by softmetz** [open-iscsi/open-iscsi#180] opened 2019-11-20 23:17 UTC
I got relases 2.1.0 from Archlinux for my Raspi today.
After the installation of the update, CHAP authentication fails with 

`Initiator reported error (24 - iSCSI login failed due to authorization failure)`

In the Log of Synology DS I found

```
kernel: [684355.950712] iSCSI: CHAP_A is not MD5.
kernel: [684355.954493] iSCSI: iSCSI: Single CHAP security negotiation failed.
kernel: [684355.960681] iSCSI: iSCSI: Login negotiation failed from [XXX.XXX.XXX.XXX
```

After downgrading to 2.0.878 things are back to normal.

**Comment by cleech** [comment] 2019-11-21 01:38
Bummer, and it seemed like the CHAP changes were going so well.

It's going to be tricky for me to figure out exactly what's going on without anything close to that setup.  If there's any chance you could share with me a network trace of a failing login attempt that would help rule out some possibilities.

I'm a bit worried that "iSCSI: CHAP_A is not MD5" on the Synology side could indicate that it's not properly taking CHAP_A to be a list of proposed algorithms for negotiation and instead is failing if anything in addition to MD5 is listed.

... and in looking at the kernel target history, that seems to be exactly the case for anything older than v3.15.  So much for this being hard to figure out I guess.  I'll see what it would take to fall back to just offering MD5 if the login is rejected at this point.  Or at least getting a configuration option in place that Lee and I had talked about to set which CHAP algorithms are offered.

**Comment by cleech** [comment] 2019-11-26 21:34
Still working on this, but I'm getting close.  Our config file code didn't really support settings of ordered lists for negotiated preferences, but I've just about got that finished.

**Comment by gonzoleeman** [comment] 2019-11-27 17:13
Interesting. I hadn't thought about the ordering. Please let me know if I can help.

**Comment by cleech** [comment] 2019-12-20 06:29
that took me longer than I expected, but PR #182 should address this when it's reviewed

**Comment by gonzoleeman** [comment] 2020-01-29 20:51
Can we close this now?

**Comment by ionphractal** [comment] 2020-02-02 12:37
Just built open-iscsi on Archlinux from git and works for me.

@gonzoleeman @cleech 
I'd be happy to have a patch release for this, because the current Arch community package is already on 2.1.0 but that release doesn't include this commit.

**Comment by gonzoleeman** [comment] 2020-02-20 22:29
@ionphractal there is some overhead involved with tagging a new version, which seems a bit much considering there aren't many changes since 2.1.0. There are only 8 changes, not counting the commits I just added for python regression testing.

What do you think @cleech ?

**Comment by gonzoleeman** [comment] 2020-02-26 19:11
@ionphractal I am tagging a new version (2.1.1). Can we close this issue?

**Comment by gonzoleeman** [comment] 2020-02-27 20:11
New version tagged.

**Closed by gonzoleeman** 2020-02-27 20:11 UTC
